apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e5ap3kn56-nodejs
  janus-idp.io/tekton: e5ap3kn56-nodejs
  backstage.io/kubernetes-id: e5ap3kn56-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e5ap3kn56-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
